name: Start Server

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest 
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}

    steps:
      # Step 1: Setup SSH for EC2
      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL

      # Step 2: Start the container
      - name: Start the container
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL << 'EOF'
            echo "Starting the container..."
            docker run -d -p 8000:8000 --name backend \
              -e MONGO_URL=${{ secrets.MONGO_URL }} \
              -e PORT=${{ secrets.PORT }} \
              -e NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL }} \
              -e RESEND_API_KEY=${{ secrets.RESEND_API_KEY }} \
              -e COMPANY_RESEND_GMAIL_ACCOUNT=${{ secrets.COMPANY_RESEND_GMAIL_ACCOUNT }} \
              ${{ secrets.DOCKER_USERNAME }}/backend:latest || { echo "Docker run failed"; exit 1; }
          EOF