name: Start Server

on:
  workflow_dispatch:

jobs:
  start-server:
    runs-on: ubuntu-latest 
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}

    steps:
      # Step 1: Setup SSH for EC2
      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: $EC2_SSH_PRIVATE_KEY
          EC2_URL: $EC2_URL

      # Step 2: Start the container
      - name: Start the container
        run: |
          ssh -o StrictHostKeyChecking=no $EC2_USERNAME@$EC2_URL << 'EOF'
            echo "Starting the container..."
            docker run -d -p 8000:8000 --name backend \
              -e MONGO_URL='${{ secrets.MONGO_URL }}' \
              -e NEXT_PUBLIC_APP_URL='${{ secrets.NEXT_PUBLIC_APP_URL }}' \
              -e RESEND_API_KEY='${{ secrets.RESEND_API_KEY }}' \
              -e COMPANY_RESEND_GMAIL_ACCOUNT='${{ secrets.COMPANY_RESEND_GMAIL_ACCOUNT }}' \
              -e STRIPE_SECRET_KEY='${{ secrets.STRIPE_SECRET_KEY }}' \
              -e STRIPE_WEBHOOK_SECRET='${{ secrets.STRIPE_WEBHOOK_SECRET }}' \
              -e STRIPE_PRICE_STAY_ROOTED='${{ secrets.STRIPE_PRICE_STAY_ROOTED }}' \
              -e STRIPE_PRICE_GLOW_UP='${{ secrets.STRIPE_PRICE_GLOW_UP }}' \
              -e STRIPE_PRICE_GLOW_UP_MONTHLY='${{ secrets.STRIPE_PRICE_GLOW_UP_MONTHLY }}' \
              -e AUTH_SECRET='${{ secrets.AUTH_SECRET }}' \
              -e JWT_SALT='${{ secrets.JWT_SALT }}' \
              -e JWT_SECRET_PHONE='${{ secrets.JWT_SECRET_PHONE }}' \
              -e STRIPE_FRONTEND_SUCCESS_CALLBACK='${{ secrets.STRIPE_FRONTEND_SUCCESS_CALLBACK }}' \
              -e STRIPE_FRONTEND_CANCEL_CALLBACK='${{ secrets.STRIPE_FRONTEND_CANCEL_CALLBACK }}' \
              -e AWS_ACCESS_KEY_ID='${{ secrets.AWS_ACCESS_KEY_ID }}' \
              -e AWS_REGION='${{ secrets.AWS_REGION }}' \
              -e AWS_SECRET_ACCESS_KEY='${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
              -e AWS_BUCKET_NAME='${{ secrets.AWS_BUCKET_NAME }}' \
              -e STRIPE_SECRET_KEY='${{ secrets.STRIPE_SECRET_KEY }}' \
              -e STRIPE_PRICE_STAY_ROOTED='${{ secrets.STRIPE_PRICE_STAY_ROOTED }}' \
              -e STRIPE_PRICE_GLOW_UP='${{ secrets.STRIPE_PRICE_GLOW_UP }}' \
              -e STRIPE_PRICE_GLOW_UP_MONTHLY='${{ secrets.STRIPE_PRICE_GLOW_UP_MONTHLY }}' \
              -e STRIPE_WEBHOOK_SECRET='${{ secrets.STRIPE_WEBHOOK_SECRET }}' \
              ${{ secrets.DOCKER_USERNAME }}/backend:latest || { echo "Docker run failed"; exit 1; }
          EOF